// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package datatype

type DtBoolean struct {
	A *bool
	B *bool
	C *bool
}

type DtBooleanNotNull struct {
	A bool
	B bool
	C bool
}

type DtInteger struct {
	A *int8
	B *int16
	C *int32
	D *int32
	E *int32
	F *int64
}

type DtIntegerNotNull struct {
	A int8
	B int16
	C int32
	D int32
	E int32
	F int64
}

type DtRealNumber struct {
	A *float64
	B *float64
	C *float64
	D *float64
	E *string
	F *string
	G *string
}

type DtRealNumberNotNull struct {
	A float64
	B float64
	C float64
	D float64
	E string
	F string
	G string
}

type DtUnsignedInteger struct {
	A *uint8
	B *uint16
	C *uint32
	D *uint32
	E *uint32
	F *uint64
}

type DtUnsignedIntegerNotNull struct {
	A uint8
	B uint16
	C uint32
	D uint32
	E uint32
	F uint64
}
