// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const placeholder = `-- name: Placeholder :many
SELECT boo from foo
`

func (q *Queries) Placeholder(ctx context.Context, aq ...AdditionalQuery) ([]sql.NullString, error) {
	query := placeholder
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var boo sql.NullString
		if err := rows.Scan(&boo); err != nil {
			return nil, err
		}
		items = append(items, boo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
