// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plugin/codegen.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CodegenService_Generate_FullMethodName = "/plugin.CodegenService/Generate"
)

// CodegenServiceClient is the client API for CodegenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodegenServiceClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type codegenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodegenServiceClient(cc grpc.ClientConnInterface) CodegenServiceClient {
	return &codegenServiceClient{cc}
}

func (c *codegenServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, CodegenService_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodegenServiceServer is the server API for CodegenService service.
// All implementations must embed UnimplementedCodegenServiceServer
// for forward compatibility
type CodegenServiceServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedCodegenServiceServer()
}

// UnimplementedCodegenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCodegenServiceServer struct {
}

func (UnimplementedCodegenServiceServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedCodegenServiceServer) mustEmbedUnimplementedCodegenServiceServer() {}

// UnsafeCodegenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodegenServiceServer will
// result in compilation errors.
type UnsafeCodegenServiceServer interface {
	mustEmbedUnimplementedCodegenServiceServer()
}

func RegisterCodegenServiceServer(s grpc.ServiceRegistrar, srv CodegenServiceServer) {
	s.RegisterService(&CodegenService_ServiceDesc, srv)
}

func _CodegenService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodegenServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodegenService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodegenServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodegenService_ServiceDesc is the grpc.ServiceDesc for CodegenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodegenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.CodegenService",
	HandlerType: (*CodegenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _CodegenService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/codegen.proto",
}
