// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
	"fmt"
)

type JobStatusType string

const (
	APPLIED  JobStatusType = "APPLIED"
	PENDING  JobStatusType = "PENDING"
	ACCEPTED JobStatusType = "ACCEPTED"
	REJECTED JobStatusType = "REJECTED"
)

func (e *JobStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusType(s)
	case string:
		*e = JobStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusType: %T", src)
	}
	return nil
}

type Order struct {
	ID     int     `db:"id",json:"id"`
	Price  float64 `db:"price",json:"price"`
	UserID int     `db:"user_id",json:"user_id"`
}

type User struct {
	ID        int            `db:"id",json:"id"`
	FirstName string         `db:"first_name",json:"first_name"`
	LastName  sql.NullString `db:"last_name",json:"last_name"`
	Age       int            `db:"age",json:"age"`
	JobStatus JobStatusType  `db:"job_status",json:"job_status"`
}
