// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_batch.sql.go

package querytest

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// QueryBatch allows queuing multiple queries to be executed in a single
// round-trip using pgx v5's QueuedQuery callback pattern. Each Queue* method
// calls pgx.Batch.Queue and registers a result callback (QueryRow, Query, or
// Exec) that is invoked when ExecuteBatch processes the batch results.
// For :exec queries, no callback is needed - errors propagate via ExecuteBatch.
//
// The Batch field is exported to allow interoperability: callers can mix
// generated Queue* calls with custom pgx batch operations on the same
// underlying pgx.Batch.
type QueryBatch struct {
	Batch *pgx.Batch
}

// NewQueryBatch creates a new QueryBatch.
func NewQueryBatch() *QueryBatch {
	return &QueryBatch{
		Batch: &pgx.Batch{},
	}
}

// ExecuteBatch sends all queued queries and closes the batch.
func (q *Queries) ExecuteBatch(ctx context.Context, batch *QueryBatch) error {
	return q.db.SendBatch(ctx, batch.Batch).Close()
}

// QueueArchiveUser queues ArchiveUser for batch execution.
// The callback fn is called with the command tag when ExecuteBatch is called.
func (b *QueryBatch) QueueArchiveUser(id int32, fn func(pgconn.CommandTag) error) {
	b.Batch.Queue(archiveUser, id).Exec(func(ct pgconn.CommandTag) error {
		return fn(ct)
	})
}

// QueueCreateUser queues CreateUser for batch execution.
// The callback fn is called when ExecuteBatch is called. The second parameter
// is false if the row was not found (no error is returned in this case).
func (b *QueryBatch) QueueCreateUser(arg CreateUserParams, fn func(MyschemaUser, bool) error) {
	b.Batch.Queue(createUser, arg.Name, arg.Email).QueryRow(func(row pgx.Row) error {
		var i MyschemaUser
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return fn(i, false)
			}
			return err
		}
		return fn(i, true)
	})
}

// QueueDeleteUser queues DeleteUser for batch execution.
// The callback fn is called with the number of rows affected when ExecuteBatch is called.
func (b *QueryBatch) QueueDeleteUser(id int32, fn func(int64) error) {
	b.Batch.Queue(deleteUser, id).Exec(func(ct pgconn.CommandTag) error {
		return fn(ct.RowsAffected())
	})
}

// QueueGetUser queues GetUser for batch execution.
// The callback fn is called when ExecuteBatch is called. The second parameter
// is false if the row was not found (no error is returned in this case).
func (b *QueryBatch) QueueGetUser(id int32, fn func(MyschemaUser, bool) error) {
	b.Batch.Queue(getUser, id).QueryRow(func(row pgx.Row) error {
		var i MyschemaUser
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return fn(i, false)
			}
			return err
		}
		return fn(i, true)
	})
}

// QueueListUsers queues ListUsers for batch execution.
// The callback fn is called with the results when ExecuteBatch is called.
func (b *QueryBatch) QueueListUsers(fn func([]MyschemaUser) error) {
	b.Batch.Queue(listUsers).Query(func(rows pgx.Rows) error {
		defer rows.Close()
		var items []MyschemaUser
		for rows.Next() {
			var i MyschemaUser
			if err := rows.Scan(
				&i.ID,
				&i.Name,
				&i.Email,
				&i.CreatedAt,
			); err != nil {
				return err
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return err
		}
		return fn(items)
	})
}

// QueueUpdateUser queues UpdateUser for batch execution.
func (b *QueryBatch) QueueUpdateUser(arg UpdateUserParams) {
	b.Batch.Queue(updateUser, arg.Name, arg.Email, arg.ID)
}
