// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const getCollection = `-- name: GetCollection :one
SELECT id, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
