// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const addAuthor = `-- name: AddAuthor :execlastid
INSERT INTO authors (
    address,
    name,
    bio
) VALUES (
    $address,
    COALESCE($cal_name, ''),
    COALESCE($cal_description, '')
)
`

type AddAuthorParams struct {
	Address        string
	CalName        interface{}
	CalDescription interface{}
}

func (q *Queries) AddAuthor(ctx context.Context, arg AddAuthorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addAuthor, arg.Address, arg.CalName, arg.CalDescription)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
