// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package querytest

import (
	"context"
)

const selectTest = `-- name: SelectTest :many
SELECT v_cid_null, v_oid_null, v_tid_null, v_xid_null, v_cid, v_oid, v_tid, v_xid
from test_table
`

func (q *Queries) SelectTest(ctx context.Context) ([]TestTable, error) {
	rows, err := q.db.Query(ctx, selectTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestTable
	for rows.Next() {
		var i TestTable
		if err := rows.Scan(
			&i.VCidNull,
			&i.VOidNull,
			&i.VTidNull,
			&i.VXidNull,
			&i.VCid,
			&i.VOid,
			&i.VTid,
			&i.VXid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
