// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getProductsWithDefault = `-- name: GetProductsWithDefault :many
SELECT id, name, ifNull(category, 'Uncategorized') AS category FROM products;
`

type GetProductsWithDefaultRow struct {
	ID       uint32
	Name     string
	Category interface{}
}

func (q *Queries) GetProductsWithDefault(ctx context.Context) ([]GetProductsWithDefaultRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsWithDefault)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithDefaultRow
	for rows.Next() {
		var i GetProductsWithDefaultRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithDescription = `-- name: GetProductsWithDescription :many
SELECT id, name, description FROM products WHERE description IS NOT NULL;
`

type GetProductsWithDescriptionRow struct {
	ID          uint32
	Name        string
	Description sql.NullString
}

func (q *Queries) GetProductsWithDescription(ctx context.Context) ([]GetProductsWithDescriptionRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsWithDescription)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithDescriptionRow
	for rows.Next() {
		var i GetProductsWithDescriptionRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithDiscount = `-- name: GetProductsWithDiscount :many
SELECT id, name, coalesce(discount, 0) AS discount FROM products;
`

type GetProductsWithDiscountRow struct {
	ID       uint32
	Name     string
	Discount interface{}
}

func (q *Queries) GetProductsWithDiscount(ctx context.Context) ([]GetProductsWithDiscountRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsWithDiscount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithDiscountRow
	for rows.Next() {
		var i GetProductsWithDiscountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Discount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithoutDescription = `-- name: GetProductsWithoutDescription :many
SELECT id, name FROM products WHERE description IS NULL;
`

type GetProductsWithoutDescriptionRow struct {
	ID   uint32
	Name string
}

func (q *Queries) GetProductsWithoutDescription(ctx context.Context) ([]GetProductsWithoutDescriptionRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsWithoutDescription)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithoutDescriptionRow
	for rows.Next() {
		var i GetProductsWithoutDescriptionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
