// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package update

import (
	"time"
)

type Author struct {
	ID        int64
	Name      string
	DeletedAt time.Time
	UpdatedAt time.Time
}

type Book struct {
	ID        int64
	IsAmazing bool
}
