// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT id, username, email, full_name, age, balance, is_active, status, role, bio, metadata, created_at, updated_at, deleted_at FROM users WHERE is_active = ?
`

func (q *Queries) GetActiveUsers(ctx context.Context, isActive bool) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsers, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Age,
			&i.Balance,
			&i.IsActive,
			&i.Status,
			&i.Role,
			&i.Bio,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, full_name, age, balance, is_active, status, role, bio, metadata, created_at, updated_at, deleted_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Age,
		&i.Balance,
		&i.IsActive,
		&i.Status,
		&i.Role,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, age, balance, is_active, status, role, bio, metadata, created_at, updated_at, deleted_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Age,
		&i.Balance,
		&i.IsActive,
		&i.Status,
		&i.Role,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
