// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package querytest

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PartyRank string

const (
	PartyRankEnsign     PartyRank = "ensign"
	PartyRankLieutenant PartyRank = "lieutenant"
	PartyRankCommander  PartyRank = "commander"
	PartyRankCaptain    PartyRank = "captain"
	PartyRankAdmiral    PartyRank = "admiral"
)

func (e *PartyRank) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartyRank(s)
	case string:
		*e = PartyRank(s)
	default:
		return fmt.Errorf("unsupported scan type for PartyRank: %T", src)
	}
	return nil
}

type NullPartyRank struct {
	PartyRank PartyRank
	Valid     bool // Valid is true if PartyRank is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartyRank) Scan(value interface{}) error {
	if value == nil {
		ns.PartyRank, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartyRank.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartyRank) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartyRank), nil
}

type Llc struct {
	PartyID           pgtype.UUID
	Name              string
	JoinedOn          pgtype.Timestamptz
	Rank              PartyRank
	LegalName         string
	IncorporationDate pgtype.Timestamp
	Region            pgtype.Text
}

type Organisation struct {
	PartyID   pgtype.UUID
	Name      string
	JoinedOn  pgtype.Timestamptz
	Rank      PartyRank
	LegalName pgtype.Text
	Region    pgtype.Text
}

type Party struct {
	PartyID  pgtype.UUID
	Name     string
	JoinedOn pgtype.Timestamptz
	Rank     PartyRank
	Region   pgtype.Text
}

type Person struct {
	PartyID   pgtype.UUID
	Name      string
	JoinedOn  pgtype.Timestamptz
	Rank      PartyRank
	FirstName string
	LastName  string
	Region    pgtype.Text
}
