// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :exec
INSERT INTO authors (id, name, bio) VALUES (?, ?, ?);
`

type CreateAuthorParams struct {
	P1 interface{}
	P2 interface{}
	P3 interface{}
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, createAuthor, arg.P1, arg.P2, arg.P3)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors WHERE id = ?;
`

type GetAuthorRow struct {
	ID   uint64
	Name string
	Bio  sql.NullString
}

func (q *Queries) GetAuthor(ctx context.Context, p1 interface{}) (GetAuthorRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, p1)
	var i GetAuthorRow
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors ORDER BY name;
`

type ListAuthorsRow struct {
	ID   uint64
	Name string
	Bio  sql.NullString
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
