// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package querytest

import (
	"database/sql"
)

type Empty struct {
	A int64
	B sql.NullInt64
}

type Foo struct {
	A int64
	B sql.NullInt64
}
