// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getAllEmployees = `-- name: GetAllEmployees :many
SELECT
    id,
    name,
    salary,
    department
FROM employees
ORDER BY id;
`

type GetAllEmployeesRow struct {
	ID         uint32
	Name       string
	Salary     float64
	Department string
}

func (q *Queries) GetAllEmployees(ctx context.Context) ([]GetAllEmployeesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEmployeesRow
	for rows.Next() {
		var i GetAllEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Salary,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeesByDepartment = `-- name: GetEmployeesByDepartment :many
SELECT
    id,
    name,
    salary
FROM employees
WHERE department = ?
ORDER BY salary DESC;
`

type GetEmployeesByDepartmentRow struct {
	ID     uint32
	Name   string
	Salary float64
}

func (q *Queries) GetEmployeesByDepartment(ctx context.Context, department string) ([]GetEmployeesByDepartmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmployeesByDepartment, department)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmployeesByDepartmentRow
	for rows.Next() {
		var i GetEmployeesByDepartmentRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Salary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
