// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
)

type Bar struct {
	A sql.NullString
	B sql.NullString
}

type Foo struct {
	A sql.NullString
	B sql.NullString
}
