package oracle

import "strings"

// oracleReservedKeywords is the set of Oracle SQL reserved words.
//
// Reference: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Oracle-SQL-Reserved-Words.html
var oracleReservedKeywords = map[string]struct{}{
	"access":     {},
	"add":        {},
	"all":        {},
	"alter":      {},
	"and":        {},
	"any":        {},
	"as":         {},
	"asc":        {},
	"audit":      {},
	"between":    {},
	"by":         {},
	"char":       {},
	"check":      {},
	"cluster":    {},
	"column":     {},
	"comment":    {},
	"compress":   {},
	"connect":    {},
	"create":     {},
	"current":    {},
	"date":       {},
	"decimal":    {},
	"default":    {},
	"delete":     {},
	"desc":       {},
	"distinct":   {},
	"drop":       {},
	"else":       {},
	"exclusive":  {},
	"exists":     {},
	"file":       {},
	"float":      {},
	"for":        {},
	"from":       {},
	"grant":      {},
	"group":      {},
	"having":     {},
	"identified": {},
	"immediate":  {},
	"in":         {},
	"increment":  {},
	"index":      {},
	"initial":    {},
	"insert":     {},
	"integer":    {},
	"intersect":  {},
	"into":       {},
	"is":         {},
	"level":      {},
	"like":       {},
	"lock":       {},
	"long":       {},
	"maxextents": {},
	"minus":      {},
	"mlslabel":   {},
	"mode":       {},
	"modify":     {},
	"noaudit":    {},
	"nocompress": {},
	"not":        {},
	"nowait":     {},
	"null":       {},
	"number":     {},
	"of":         {},
	"offline":    {},
	"on":         {},
	"online":     {},
	"option":     {},
	"or":         {},
	"order":      {},
	"pctfree":    {},
	"prior":      {},
	"privileges": {},
	"public":     {},
	"raw":        {},
	"rename":     {},
	"resource":   {},
	"revoke":     {},
	"row":        {},
	"rowid":      {},
	"rownum":     {},
	"rows":       {},
	"select":     {},
	"session":    {},
	"set":        {},
	"share":      {},
	"size":       {},
	"smallint":   {},
	"start":      {},
	"successful": {},
	"synonym":    {},
	"sysdate":    {},
	"table":      {},
	"then":       {},
	"to":         {},
	"trigger":    {},
	"uid":        {},
	"union":      {},
	"unique":     {},
	"update":     {},
	"user":       {},
	"validate":   {},
	"values":     {},
	"varchar":    {},
	"varchar2":   {},
	"view":       {},
	"whenever":   {},
	"where":      {},
	"with":       {},
}

// IsReservedKeyword reports whether s (case-insensitive) is an Oracle reserved
// SQL keyword. It satisfies the compiler.Parser interface.
func (p *Parser) IsReservedKeyword(s string) bool {
	_, ok := oracleReservedKeywords[strings.ToLower(s)]
	return ok
}
