// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
)

type JobStatusType string

const (
	APPLIED  JobStatusType = "APPLIED"
	PENDING  JobStatusType = "PENDING"
	ACCEPTED JobStatusType = "ACCEPTED"
	REJECTED JobStatusType = "REJECTED"
)

func (e *JobStatusType) Scan(src interface{}) error {
	*e = JobStatusType(src.([]byte))
	return nil
}

type Order struct {
	ID     int
	Price  float64
	UserID int
}

type User struct {
	ID        int
	FirstName string
	LastName  sql.NullString
	Age       int
	JobStatus JobStatusType
}
