// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"context"
)

type Querier interface {
	AllTypes(ctx context.Context) ([]Thing, error)
	Casts(ctx context.Context, arg CastsParams) (CastsRow, error)
	Params(ctx context.Context, arg ParamsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
