package ydb

import "strings"


func (p *Parser) IsReservedKeyword(s string) bool {
	switch strings.ToLower(s) {
	case "abort":
	case "action":
	case "add":
	case "after":
	case "all":
	case "alter":
	case "analyze":
	case "and":
	case "ansi":
	case "any":
	case "array":
	case "as":
	case "asc":
	case "assume":
	case "asymmetric":
	case "async":
	case "at":
	case "attach":
	case "attributes":
	case "autoincrement":
	case "automap":
	case "backup":
	case "batch":
	case "collection":
	case "before":
	case "begin":
	case "bernoulli":
	case "between":
	case "bitcast":
	case "by":
	case "callable":
	case "cascade":
	case "case":
	case "cast":
	case "changefeed":
	case "check":
	case "classifier":
	case "collate":
	case "column":
	case "columns":
	case "commit":
	case "compact":
	case "conditional":
	case "conflict":
	case "connect":
	case "constraint":
	case "consumer":
	case "cover":
	case "create":
	case "cross":
	case "cube":
	case "current":
	case "current_date":
	case "current_time":
	case "current_timestamp":
	case "data":
	case "database":
	case "decimal":
	case "declare":
	case "default":
	case "deferrable":
	case "deferred":
	case "define":
	case "delete":
	case "desc":
	case "describe":
	case "detach":
	case "dict":
	case "directory":
	case "disable":
	case "discard":
	case "distinct":
	case "do":
	case "drop":
	case "each":
	case "else":
	case "empty":
	case "empty_action":
	case "encrypted":
	case "end":
	case "enum":
	case "erase":
	case "error":
	case "escape":
	case "evaluate":
	case "except":
	case "exclude":
	case "exclusion":
	case "exclusive":
	case "exists":
	case "explain":
	case "export":
	case "external":
	case "fail":
	case "false":
	case "family":
	case "filter":
	case "first":
	case "flatten":
	case "flow":
	case "following":
	case "for":
	case "foreign":
	case "from":
	case "full":
	case "function":
	case "glob":
	case "global":
	case "grant":
	case "group":
	case "grouping":
	case "groups":
	case "hash":
	case "having":
	case "hop":
	case "if":
	case "ignore":
	case "ilike":
	case "immediate":
	case "import":
	case "in":
	case "increment":
	case "incremental":
	case "index":
	case "indexed":
	case "inherits":
	case "initial":
	case "initially":
	case "inner":
	case "insert":
	case "instead":
	case "intersect":
	case "into":
	case "is":
	case "isnull":
	case "join":
	case "json_exists":
	case "json_query":
	case "json_value":
	case "key":
	case "last":
	case "left":
	case "legacy":
	case "like":
	case "limit":
	case "list":
	case "local":
	case "login":
	case "manage":
	case "match":
	case "matches":
	case "match_recognize":
	case "measures":
	case "microseconds":
	case "milliseconds":
	case "modify":
	case "nanoseconds":
	case "natural":
	case "next":
	case "no":
	case "nologin":
	case "not":
	case "notnull":
	case "null":
	case "nulls":
	case "object":
	case "of":
	case "offset":
	case "omit":
	case "on":
	case "one":
	case "only":
	case "option":
	case "optional":
	case "or":
	case "order":
	case "others":
	case "outer":
	case "over":
	case "owner":
	case "parallel":
	case "partition":
	case "passing":
	case "password":
	case "past":
	case "pattern":
	case "per":
	case "permute":
	case "plan":
	case "pool":
	case "pragma":
	case "preceding":
	case "presort":
	case "primary":
	case "privileges":
	case "process":
	case "query":
	case "queue":
	case "raise":
	case "range":
	case "reduce":
	case "references":
	case "regexp":
	case "reindex":
	case "release":
	case "remove":
	case "rename":
	case "repeatable":
	case "replace":
	case "replication":
	case "reset":
	case "resource":
	case "respect":
	case "restart":
	case "restore":
	case "restrict":
	case "result":
	case "return":
	case "returning":
	case "revert":
	case "revoke":
	case "right":
	case "rlike":
	case "rollback":
	case "rollup":
	case "row":
	case "rows":
	case "sample":
	case "savepoint":
	case "schema":
	case "seconds":
	case "seek":
	case "select":
	case "semi":
	case "set":
	case "sets":
	case "show":
	case "tskip":
	case "sequence":
	case "source":
	case "start":
	case "stream":
	case "struct":
	case "subquery":
	case "subset":
	case "symbols":
	case "symmetric":
	case "sync":
	case "system":
	case "table":
	case "tables":
	case "tablesample":
	case "tablestore":
	case "tagged":
	case "temp":
	case "temporary":
	case "then":
	case "ties":
	case "to":
	case "topic":
	case "transaction":
	case "transfer":
	case "trigger":
	case "true":
	case "tuple":
	case "type":
	case "unbounded":
	case "unconditional":
	case "union":
	case "unique":
	case "unknown":
	case "unmatched":
	case "update":
	case "upsert":
	case "use":
	case "user":
	case "using":
	case "vacuum":
	case "values":
	case "variant":
	case "view":
	case "virtual":
	case "when":
	case "where":
	case "window":
	case "with":
	case "without":
	case "wrapper":
	case "xor":
	default:
		return false
	}
	return true
}
