// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package override

type Bar struct {
	Other      string `utype:"notnull_text"`
	AlsoTagged string `also:"tagged" utype:"notnull_text"`
}

type Baz struct {
	Other      string `utype:"notnull_text"`
	AlsoTagged string `also:"tagged" utype:"notnull_text"`
}

type Foo struct {
	Other    string `utype:"notnull_text"`
	Tagged   string `a:"b" utype:"notnull_text" x:"y,z"`
	Nulltext string `utype:"nullable_text"`
}
