// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package replica

import (
	"context"

	models "github.com/sqlc-dev/sqlc/endtoend/output_models_shared/postgresql/model"
)

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, status FROM authors ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]models.Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.Author
	for rows.Next() {
		var i models.Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsByStatus = `-- name: ListAuthorsByStatus :many
SELECT id, name, status FROM authors WHERE status = $1 ORDER BY name
`

func (q *Queries) ListAuthorsByStatus(ctx context.Context, status models.Status) ([]models.Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.Author
	for rows.Next() {
		var i models.Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
