// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package querytest

import (
	"context"
	"encoding/json"
)

const selectFieldJson = `-- name: SelectFieldJson :one
SELECT bar FROM foo WHERE bar -> 'field_name' = $1
`

func (q *Queries) SelectFieldJson(ctx context.Context, dollar_1 json.RawMessage) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, selectFieldJson, dollar_1)
	var bar json.RawMessage
	err := row.Scan(&bar)
	return bar, err
}

const selectFieldText = `-- name: SelectFieldText :one
SELECT bar FROM foo WHERE bar ->> 'field_name' = $1
`

func (q *Queries) SelectFieldText(ctx context.Context, dollar_1 string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, selectFieldText, dollar_1)
	var bar json.RawMessage
	err := row.Scan(&bar)
	return bar, err
}

const selectTypeCast = `-- name: SelectTypeCast :one
SELECT bar FROM foo WHERE (bar ->> 'field_name')::text = $1
`

func (q *Queries) SelectTypeCast(ctx context.Context, dollar_1 string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, selectTypeCast, dollar_1)
	var bar json.RawMessage
	err := row.Scan(&bar)
	return bar, err
}
