// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, status) VALUES ($1, $2) RETURNING id, title, status;
`

type CreateTaskParams struct {
	Column1 sql.NullString
	Column2 NullStatus
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Column1, arg.Column2)
	var i Task
	err := row.Scan(&i.ID, &i.Title, &i.Status)
	return i, err
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT id, title, status FROM tasks WHERE status = $1;
`

func (q *Queries) GetTasksByStatus(ctx context.Context, dollar_1 NullStatus) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, status FROM tasks;
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
