// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID    int32
	Title sql.NullString
}

func (t *Bar) GetID() int32 {
	return t.ID
}
func (t *Bar) GetTitle() sql.NullString {
	return t.Title
}

type Foo struct {
	ID int32
}

func (t *Foo) GetID() int32 {
	return t.ID
}
