// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Bar struct {
	ColA sql.NullBool
	ColB sql.NullBool
}

type Foo struct {
	ColA bool
	ColB bool
}
