// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getHighEarners = `-- name: GetHighEarners :many
WITH high_earners AS (
  SELECT id, name, salary FROM employees WHERE salary > ?
)
SELECT id, name, salary FROM high_earners ORDER BY salary DESC;
`

type GetHighEarnersRow struct {
	ID     uint32
	Name   string
	Salary uint32
}

func (q *Queries) GetHighEarners(ctx context.Context, salary uint32) ([]GetHighEarnersRow, error) {
	rows, err := q.db.QueryContext(ctx, getHighEarners, salary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHighEarnersRow
	for rows.Next() {
		var i GetHighEarnersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Salary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipleCTEs = `-- name: GetMultipleCTEs :many
WITH emp_data AS (
  SELECT id, name, salary FROM employees
),
filtered AS (
  SELECT id, name, salary FROM emp_data WHERE salary > ?
)
SELECT id, name FROM filtered;
`

type GetMultipleCTEsRow struct {
	ID   uint32
	Name string
}

func (q *Queries) GetMultipleCTEs(ctx context.Context, salary uint32) ([]GetMultipleCTEsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMultipleCTEs, salary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMultipleCTEsRow
	for rows.Next() {
		var i GetMultipleCTEsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
