// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package querytest

import (
	"context"
)

const insertFoo = `-- name: InsertFoo :exec
INSERT INTO foo (
    a,
    b,
    c,
    d
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING a, json(b), c, json(d)
`

type InsertFooParams struct {
	A []byte
	B []byte
	C []byte
	D []byte
}

func (q *Queries) InsertFoo(ctx context.Context, arg InsertFooParams) error {
	_, err := q.db.ExecContext(ctx, insertFoo,
		arg.A,
		arg.B,
		arg.C,
		arg.D,
	)
	return err
}

const selectFoo = `-- name: SelectFoo :exec
SELECT a, json(b), c, json(d) FROM foo
`

func (q *Queries) SelectFoo(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, selectFoo)
	return err
}
