// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const placeholder = `-- name: Placeholder :exec
SELECT 1
`

func (q *Queries) Placeholder(ctx context.Context, opts ...query.ExecuteOption) error {
	err := q.db.Exec(ctx, placeholder, opts...)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}
	return nil
}
