// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const foo = `-- name: Foo :one
SELECT id, bebra FROM AS_TABLE($table) AS t(id, bebra)
`

type FooRow struct {
	ID    interface{}
	Bebra interface{}
}

func (q *Queries) Foo(ctx context.Context, table interface{}) (FooRow, error) {
	row := q.db.QueryRowContext(ctx, foo, table)
	var i FooRow
	err := row.Scan(&i.ID, &i.Bebra)
	return i, err
}
