// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package querytest

import (
	"context"
)

const limitMe = `-- name: LimitMe :exec
UPDATE foo SET bar='baz' LIMIT ?
`

func (q *Queries) LimitMe(ctx context.Context, limit int32) error {
	query := limitMe
	queryParams := []interface{}{limit}

	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const limitMeToo = `-- name: LimitMeToo :exec
DELETE FROM foo LIMIT ?
`

func (q *Queries) LimitMeToo(ctx context.Context, limit int32) error {
	query := limitMeToo
	queryParams := []interface{}{limit}

	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
