// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const nearestTo = `-- name: NearestTo :many
SELECT x, y
FROM nearest_to($1::point_input)
`

type NearestToRow struct {
	X pgtype.Int4
	Y pgtype.Int4
}

func (q *Queries) NearestTo(ctx context.Context, p PointInput) ([]NearestToRow, error) {
	rows, err := q.db.Query(ctx, nearestTo, p)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NearestToRow
	for rows.Next() {
		var i NearestToRow
		if err := rows.Scan(&i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
