// Code generated by sqlc. DO NOT EDIT.

package ondeck

import (
	"database/sql"
	"time"
)

type Status string

const (
	StatusOpen   Status = "open"
	StatusClosed Status = "closed"
)

func (e *Status) Scan(src interface{}) error {
	*e = Status(src.([]byte))
	return nil
}

type City struct {
	Slug string
	Name string
}

type Venue struct {
	ID              int32
	CreateAt        time.Time
	Status          Status
	Slug            string
	Name            string
	City            string
	SpotifyPlaylist string
	SongkickID      sql.NullString
}
