// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package querytest

import ()

type Author struct {
	ID   int32
	Name string
}

type AuthorBook struct {
	AuthorID int32
	BookID   int32
}

type Book struct {
	ID    int32
	Title string
}
