// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const inlineHint = `-- name: InlineHint :one
SELECT /*+ MAX_EXECUTION_TIME(1000) */ bar FROM foo LIMIT 1
`

func (q *Queries) InlineHint(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, inlineHint)
	var bar sql.NullString
	err := row.Scan(&bar)
	return bar, err
}

const multilineHint = `-- name: MultilineHint :one
SELECT
/*+ MAX_EXECUTION_TIME(1000) */
bar
FROM foo
LIMIT 1
`

func (q *Queries) MultilineHint(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, multilineHint)
	var bar sql.NullString
	err := row.Scan(&bar)
	return bar, err
}
