// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const getBars = `-- name: GetBars :many
SELECT DISTINCT id, name
FROM bar
`

func (q *Queries) GetBars(ctx context.Context, opts ...query.ExecuteOption) ([]Bar, error) {
	result, err := q.db.QueryResultSet(ctx, getBars, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []Bar
	for row, err := range result.Rows(ctx) {
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var i Bar
		if err := row.Scan(&i.ID, &i.Name); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, i)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}
