// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package mysql

import (
	"context"
	"database/sql"
)

const findEntry = `-- name: FindEntry :one
SELECT id, value, code FROM entries
WHERE value = ? AND code = ?
`

type FindEntryParams struct {
	Value sql.NullString `backend:"mysql"`
	Code  []byte         `backend:"mysql"`
}

func (q *Queries) FindEntry(ctx context.Context, arg FindEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, findEntry, arg.Value, arg.Code)
	var i Entry
	err := row.Scan(&i.ID, &i.Value, &i.Code)
	return i, err
}
