// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, payload, meta) VALUES ($1, $2, $3);
`

type CreateEventParams struct {
	ID      int32
	Payload string
	Meta    sql.NullString
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent, arg.ID, arg.Payload, arg.Meta)
	return err
}

const eventKind = `-- name: EventKind :one
SELECT json_extract(payload, '$.kind') AS kind, json_extract_string(payload, '$.kind') AS kind_text
FROM events WHERE id = $1;
`

type EventKindRow struct {
	Kind     any
	KindText string
}

func (q *Queries) EventKind(ctx context.Context, id int32) (EventKindRow, error) {
	row := q.db.QueryRowContext(ctx, eventKind, id)
	var i EventKindRow
	err := row.Scan(&i.Kind, &i.KindText)
	return i, err
}

const eventsByPayload = `-- name: EventsByPayload :many
SELECT id FROM events WHERE payload = $1;
`

func (q *Queries) EventsByPayload(ctx context.Context, payload string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, eventsByPayload, payload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, payload, meta FROM events WHERE id = $1;
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(&i.ID, &i.Payload, &i.Meta)
	return i, err
}

const payloadText = `-- name: PayloadText :one
SELECT CAST(payload AS VARCHAR) AS payload_text FROM events WHERE id = $1;
`

func (q *Queries) PayloadText(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, payloadText, id)
	var payload_text string
	err := row.Scan(&payload_text)
	return payload_text, err
}
