// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const getOrderItemsWithProduct = `-- name: GetOrderItemsWithProduct :many
SELECT oi.quantity, oi.unit_price, p.name AS product_name
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.id
`

type GetOrderItemsWithProductRow struct {
	Quantity    int64
	UnitPrice   float64
	ProductName string
}

func (q *Queries) GetOrderItemsWithProduct(ctx context.Context) ([]GetOrderItemsWithProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsWithProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsWithProductRow
	for rows.Next() {
		var i GetOrderItemsWithProductRow
		if err := rows.Scan(&i.Quantity, &i.UnitPrice, &i.ProductName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersWithUser = `-- name: GetOrdersWithUser :many
SELECT o.id, o.status, o.total_amount, u.username, u.email
FROM orders o
INNER JOIN users u ON o.user_id = u.id
`

type GetOrdersWithUserRow struct {
	ID          int64
	Status      string
	TotalAmount float64
	Username    string
	Email       string
}

func (q *Queries) GetOrdersWithUser(ctx context.Context) ([]GetOrdersWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersWithUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersWithUserRow
	for rows.Next() {
		var i GetOrdersWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
