// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"net"
)

type Bar struct {
	Addr         net.HardwareAddr
	NullableAddr net.HardwareAddr
}

type Foo struct {
	PresentIp    net.IP
	NullableIp   net.IP
	PresentCidr  net.IP
	NullableCidr net.IP
}
