// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price)
VALUES (?, ?)
RETURNING id, category_id, name, description, price, quantity, weight, is_available, tags, created_at, updated_at
`

type CreateProductParams struct {
	Name  string
	Price float64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.Weight,
		&i.IsAvailable,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email)
VALUES (?, ?)
RETURNING id, username, email, full_name, age, balance, is_active, status, role, bio, metadata, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Age,
		&i.Balance,
		&i.IsActive,
		&i.Status,
		&i.Role,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
