// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Routergroup struct {
	Groupid                uint32
	Groupname              string
	Defaultconfigid        sql.NullInt32
	Defaultfirmwareversion sql.NullString
	Parentgroupid          sql.NullInt32
	Firmwarepolicy         sql.NullString
	Styles                 sql.NullString
}
