// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Event struct {
	ID         uint32
	Name       string
	Timestamp  time.Time
	Properties string
}

type Product struct {
	ID      uint32
	Name    string
	Tags    []string
	Ratings []string
}
