# Code generated by sqlc. DO NOT EDIT.


import pydantic


# Enums

# Models
class Jet(pydantic.BaseModel):
    id: int
    pilot_id: int
    age: int
    name: str
    color: str


class Language(pydantic.BaseModel):
    id: int
    language: str


class Pilot(pydantic.BaseModel):
    id: int
    name: str


class PilotLanguage(pydantic.BaseModel):
    pilot_id: int
    language_id: int


