// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"database/sql"
)

type InsertValuesParams struct {
	A sql.NullString
	B sql.NullInt32
}
