// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
)

type Metric struct {
	ID    int32
	Value sql.NullFloat64
	Count int32
	Ratio sql.NullFloat64
}
