// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package querytest

import (
	"fmt"
)

type FooTypeUserRole string

const (
	FooTypeUserRoleAdmin FooTypeUserRole = "admin"
	FooTypeUserRoleUser  FooTypeUserRole = "user"
)

func (e *FooTypeUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FooTypeUserRole(s)
	case string:
		*e = FooTypeUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for FooTypeUserRole: %T", src)
	}
	return nil
}

type FooUser struct {
	Role FooTypeUserRole
}
