// Code generated by sqlc. DO NOT EDIT.

package querytest

import ()

type Foo struct {
	Bar string
	Bat string
}

func (t *Foo) GetBar() string {
	return t.Bar
}
func (t *Foo) GetBat() string {
	return t.Bat
}
