// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

func PgBuffercache() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = []*catalog.Function{
		{
			Name:       "pg_buffercache_pages",
			Args:       []*catalog.Argument{},
			ReturnType: &ast.TypeName{Name: "record"},
		},
	}
	return s
}
