// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForIgnoreLocations uint32 = 1

func convertRowsForIgnoreLocations(w *io.PipeWriter, arg []IgnoreLocationsParams) {
	e := mysqltsv.NewEncoder(w, 5, nil)
	for _, row := range arg {
		e.AppendString(row.ID)
		e.AppendString(row.Name)
		e.AppendString(row.Address)
		e.AppendValue(row.Latitude)
		e.AppendValue(row.Longitude)
	}
	w.CloseWithError(e.Close())
}

// IgnoreLocations uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) IgnoreLocations(ctx context.Context, arg []IgnoreLocationsParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("IgnoreLocations_%d", atomic.AddUint32(&readerHandlerSequenceForIgnoreLocations, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForIgnoreLocations(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' IGNORE INTO TABLE `locations` %s (id, name, address, latitude, longitude)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

var readerHandlerSequenceForUpsertLocations uint32 = 1

func convertRowsForUpsertLocations(w *io.PipeWriter, arg []UpsertLocationsParams) {
	e := mysqltsv.NewEncoder(w, 5, nil)
	for _, row := range arg {
		e.AppendString(row.ID)
		e.AppendString(row.Name)
		e.AppendString(row.Address)
		e.AppendValue(row.Latitude)
		e.AppendValue(row.Longitude)
	}
	w.CloseWithError(e.Close())
}

// UpsertLocations uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func (q *Queries) UpsertLocations(ctx context.Context, arg []UpsertLocationsParams) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("UpsertLocations_%d", atomic.AddUint32(&readerHandlerSequenceForUpsertLocations, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForUpsertLocations(pw, arg)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := q.db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' REPLACE INTO TABLE `locations` %s (id, name, address, latitude, longitude)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
