// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ChatMessage struct {
	ID        string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
