// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: kotlin/ast.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//	*Node_Comment
	//	*Node_File
	//	*Node_PackageDirective
	//	*Node_DotQualifiedExpression
	//	*Node_NameReferenceExpression
	//	*Node_Class
	//	*Node_DeclarationModifierList
	//	*Node_PrimaryConstructor
	//	*Node_Parameter
	//	*Node_ParameterList
	//	*Node_TypeReference
	//	*Node_UserType
	//	*Node_NullableType
	Node isNode_Node `protobuf_oneof:"node"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{0}
}

func (m *Node) GetNode() isNode_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *Node) GetComment() *Comment {
	if x, ok := x.GetNode().(*Node_Comment); ok {
		return x.Comment
	}
	return nil
}

func (x *Node) GetFile() *File {
	if x, ok := x.GetNode().(*Node_File); ok {
		return x.File
	}
	return nil
}

func (x *Node) GetPackageDirective() *PackageDirective {
	if x, ok := x.GetNode().(*Node_PackageDirective); ok {
		return x.PackageDirective
	}
	return nil
}

func (x *Node) GetDotQualifiedExpression() *DotQualifiedExpression {
	if x, ok := x.GetNode().(*Node_DotQualifiedExpression); ok {
		return x.DotQualifiedExpression
	}
	return nil
}

func (x *Node) GetNameReferenceExpression() *NameReferenceExpression {
	if x, ok := x.GetNode().(*Node_NameReferenceExpression); ok {
		return x.NameReferenceExpression
	}
	return nil
}

func (x *Node) GetClass() *Class {
	if x, ok := x.GetNode().(*Node_Class); ok {
		return x.Class
	}
	return nil
}

func (x *Node) GetDeclarationModifierList() *DeclarationModifierList {
	if x, ok := x.GetNode().(*Node_DeclarationModifierList); ok {
		return x.DeclarationModifierList
	}
	return nil
}

func (x *Node) GetPrimaryConstructor() *PrimaryConstructor {
	if x, ok := x.GetNode().(*Node_PrimaryConstructor); ok {
		return x.PrimaryConstructor
	}
	return nil
}

func (x *Node) GetParameter() *Parameter {
	if x, ok := x.GetNode().(*Node_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (x *Node) GetParameterList() *ParameterList {
	if x, ok := x.GetNode().(*Node_ParameterList); ok {
		return x.ParameterList
	}
	return nil
}

func (x *Node) GetTypeReference() *TypeReference {
	if x, ok := x.GetNode().(*Node_TypeReference); ok {
		return x.TypeReference
	}
	return nil
}

func (x *Node) GetUserType() *UserType {
	if x, ok := x.GetNode().(*Node_UserType); ok {
		return x.UserType
	}
	return nil
}

func (x *Node) GetNullableType() *NullableType {
	if x, ok := x.GetNode().(*Node_NullableType); ok {
		return x.NullableType
	}
	return nil
}

type isNode_Node interface {
	isNode_Node()
}

type Node_Comment struct {
	Comment *Comment `protobuf:"bytes,1,opt,name=comment,json=Comment,proto3,oneof"`
}

type Node_File struct {
	File *File `protobuf:"bytes,2,opt,name=file,json=File,proto3,oneof"`
}

type Node_PackageDirective struct {
	PackageDirective *PackageDirective `protobuf:"bytes,3,opt,name=package_directive,json=PackageDirective,proto3,oneof"`
}

type Node_DotQualifiedExpression struct {
	DotQualifiedExpression *DotQualifiedExpression `protobuf:"bytes,4,opt,name=dot_qualified_expression,json=DotQualifiedExpression,proto3,oneof"`
}

type Node_NameReferenceExpression struct {
	NameReferenceExpression *NameReferenceExpression `protobuf:"bytes,5,opt,name=name_reference_expression,json=NameReferenceExpression,proto3,oneof"`
}

type Node_Class struct {
	Class *Class `protobuf:"bytes,6,opt,name=class,json=Class,proto3,oneof"`
}

type Node_DeclarationModifierList struct {
	DeclarationModifierList *DeclarationModifierList `protobuf:"bytes,7,opt,name=declaration_modifier_list,json=DeclarationModifierList,proto3,oneof"`
}

type Node_PrimaryConstructor struct {
	PrimaryConstructor *PrimaryConstructor `protobuf:"bytes,8,opt,name=primary_constructor,json=PrimaryConstructor,proto3,oneof"`
}

type Node_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,9,opt,name=parameter,json=Parameter,proto3,oneof"`
}

type Node_ParameterList struct {
	ParameterList *ParameterList `protobuf:"bytes,10,opt,name=parameter_list,json=ParameterList,proto3,oneof"`
}

type Node_TypeReference struct {
	TypeReference *TypeReference `protobuf:"bytes,11,opt,name=type_reference,json=TypeReference,proto3,oneof"`
}

type Node_UserType struct {
	UserType *UserType `protobuf:"bytes,12,opt,name=user_type,json=UserType,proto3,oneof"`
}

type Node_NullableType struct {
	NullableType *NullableType `protobuf:"bytes,13,opt,name=nullable_type,json=NullableType,proto3,oneof"`
}

func (*Node_Comment) isNode_Node() {}

func (*Node_File) isNode_Node() {}

func (*Node_PackageDirective) isNode_Node() {}

func (*Node_DotQualifiedExpression) isNode_Node() {}

func (*Node_NameReferenceExpression) isNode_Node() {}

func (*Node_Class) isNode_Node() {}

func (*Node_DeclarationModifierList) isNode_Node() {}

func (*Node_PrimaryConstructor) isNode_Node() {}

func (*Node_Parameter) isNode_Node() {}

func (*Node_ParameterList) isNode_Node() {}

func (*Node_TypeReference) isNode_Node() {}

func (*Node_UserType) isNode_Node() {}

func (*Node_NullableType) isNode_Node() {}

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body        []*Node                  `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	Modifiers   *DeclarationModifierList `protobuf:"bytes,3,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	Constructor *PrimaryConstructor      `protobuf:"bytes,4,opt,name=constructor,proto3" json:"constructor,omitempty"`
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{1}
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Class) GetModifiers() *DeclarationModifierList {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *Class) GetConstructor() *PrimaryConstructor {
	if x != nil {
		return x.Constructor
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeclarationModifierList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Annotations []string `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *DeclarationModifierList) Reset() {
	*x = DeclarationModifierList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclarationModifierList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclarationModifierList) ProtoMessage() {}

func (x *DeclarationModifierList) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclarationModifierList.ProtoReflect.Descriptor instead.
func (*DeclarationModifierList) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{3}
}

func (x *DeclarationModifierList) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type DotQualifiedExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver *Node `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Selector *Node `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *DotQualifiedExpression) Reset() {
	*x = DotQualifiedExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DotQualifiedExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotQualifiedExpression) ProtoMessage() {}

func (x *DotQualifiedExpression) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotQualifiedExpression.ProtoReflect.Descriptor instead.
func (*DotQualifiedExpression) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{4}
}

func (x *DotQualifiedExpression) GetReceiver() *Node {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *DotQualifiedExpression) GetSelector() *Node {
	if x != nil {
		return x.Selector
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []*Node `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

type NameReferenceExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NameReferenceExpression) Reset() {
	*x = NameReferenceExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameReferenceExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameReferenceExpression) ProtoMessage() {}

func (x *NameReferenceExpression) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameReferenceExpression.ProtoReflect.Descriptor instead.
func (*NameReferenceExpression) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{6}
}

func (x *NameReferenceExpression) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NullableType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InnerType *Node `protobuf:"bytes,1,opt,name=inner_type,proto3" json:"inner_type,omitempty"`
}

func (x *NullableType) Reset() {
	*x = NullableType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableType) ProtoMessage() {}

func (x *NullableType) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableType.ProtoReflect.Descriptor instead.
func (*NullableType) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{7}
}

func (x *NullableType) GetInnerType() *Node {
	if x != nil {
		return x.InnerType
	}
	return nil
}

type PackageDirective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Node `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PackageDirective) Reset() {
	*x = PackageDirective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDirective) ProtoMessage() {}

func (x *PackageDirective) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDirective.ProtoReflect.Descriptor instead.
func (*PackageDirective) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{8}
}

func (x *PackageDirective) GetName() *Node {
	if x != nil {
		return x.Name
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ref  *TypeReference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{9}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetRef() *TypeReference {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ParameterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parameters []*Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *ParameterList) Reset() {
	*x = ParameterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterList) ProtoMessage() {}

func (x *ParameterList) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterList.ProtoReflect.Descriptor instead.
func (*ParameterList) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{10}
}

func (x *ParameterList) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type TypeReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *Node `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *TypeReference) Reset() {
	*x = TypeReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeReference) ProtoMessage() {}

func (x *TypeReference) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeReference.ProtoReflect.Descriptor instead.
func (*TypeReference) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{11}
}

func (x *TypeReference) GetElement() *Node {
	if x != nil {
		return x.Element
	}
	return nil
}

type UserType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReferenceExpression *NameReferenceExpression `protobuf:"bytes,1,opt,name=reference_expression,proto3" json:"reference_expression,omitempty"`
}

func (x *UserType) Reset() {
	*x = UserType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserType) ProtoMessage() {}

func (x *UserType) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserType.ProtoReflect.Descriptor instead.
func (*UserType) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{12}
}

func (x *UserType) GetReferenceExpression() *NameReferenceExpression {
	if x != nil {
		return x.ReferenceExpression
	}
	return nil
}

type PrimaryConstructor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueParameterList *ParameterList `protobuf:"bytes,1,opt,name=value_parameter_list,proto3" json:"value_parameter_list,omitempty"`
}

func (x *PrimaryConstructor) Reset() {
	*x = PrimaryConstructor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kotlin_ast_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimaryConstructor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryConstructor) ProtoMessage() {}

func (x *PrimaryConstructor) ProtoReflect() protoreflect.Message {
	mi := &file_kotlin_ast_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryConstructor.ProtoReflect.Descriptor instead.
func (*PrimaryConstructor) Descriptor() ([]byte, []int) {
	return file_kotlin_ast_proto_rawDescGZIP(), []int{13}
}

func (x *PrimaryConstructor) GetValueParameterList() *ParameterList {
	if x != nil {
		return x.ValueParameterList
	}
	return nil
}

var File_kotlin_ast_proto protoreflect.FileDescriptor

var file_kotlin_ast_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2f, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x22, 0x8d,
	0x07, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69,
	0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e,
	0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x4b, 0x0a, 0x11, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x6f,
	0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x10, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x5e, 0x0a,
	0x18, 0x64, 0x6f, 0x74, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x44, 0x6f, 0x74,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x16, 0x44, 0x6f, 0x74, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x61, 0x0a,
	0x19, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x17, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x48, 0x00, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x61, 0x0a, 0x19, 0x64,
	0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x63, 0x6c,
	0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x51,
	0x0a, 0x13, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x6f,
	0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x12, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x35, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x0e,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x0d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b,
	0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0xc6,
	0x01, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x12, 0x41, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x1d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3b, 0x0a, 0x17, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x74, 0x0a, 0x16, 0x44, 0x6f, 0x74, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x08, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x24, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2d, 0x0a, 0x17, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x03, 0x72, 0x65, 0x66,
	0x22, 0x46, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x35, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61,
	0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x57, 0x0a, 0x14, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x12, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x4d, 0x0a, 0x14, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x14, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x79,
	0x6c, 0x65, 0x63, 0x6f, 0x6e, 0x72, 0x6f, 0x79, 0x2f, 0x73, 0x71, 0x6c, 0x63, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2f, 0x61, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kotlin_ast_proto_rawDescOnce sync.Once
	file_kotlin_ast_proto_rawDescData = file_kotlin_ast_proto_rawDesc
)

func file_kotlin_ast_proto_rawDescGZIP() []byte {
	file_kotlin_ast_proto_rawDescOnce.Do(func() {
		file_kotlin_ast_proto_rawDescData = protoimpl.X.CompressGZIP(file_kotlin_ast_proto_rawDescData)
	})
	return file_kotlin_ast_proto_rawDescData
}

var file_kotlin_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kotlin_ast_proto_goTypes = []interface{}{
	(*Node)(nil),                    // 0: kotlin.ast.Node
	(*Class)(nil),                   // 1: kotlin.ast.Class
	(*Comment)(nil),                 // 2: kotlin.ast.Comment
	(*DeclarationModifierList)(nil), // 3: kotlin.ast.DeclarationModifierList
	(*DotQualifiedExpression)(nil),  // 4: kotlin.ast.DotQualifiedExpression
	(*File)(nil),                    // 5: kotlin.ast.File
	(*NameReferenceExpression)(nil), // 6: kotlin.ast.NameReferenceExpression
	(*NullableType)(nil),            // 7: kotlin.ast.NullableType
	(*PackageDirective)(nil),        // 8: kotlin.ast.PackageDirective
	(*Parameter)(nil),               // 9: kotlin.ast.Parameter
	(*ParameterList)(nil),           // 10: kotlin.ast.ParameterList
	(*TypeReference)(nil),           // 11: kotlin.ast.TypeReference
	(*UserType)(nil),                // 12: kotlin.ast.UserType
	(*PrimaryConstructor)(nil),      // 13: kotlin.ast.PrimaryConstructor
}
var file_kotlin_ast_proto_depIdxs = []int32{
	2,  // 0: kotlin.ast.Node.comment:type_name -> kotlin.ast.Comment
	5,  // 1: kotlin.ast.Node.file:type_name -> kotlin.ast.File
	8,  // 2: kotlin.ast.Node.package_directive:type_name -> kotlin.ast.PackageDirective
	4,  // 3: kotlin.ast.Node.dot_qualified_expression:type_name -> kotlin.ast.DotQualifiedExpression
	6,  // 4: kotlin.ast.Node.name_reference_expression:type_name -> kotlin.ast.NameReferenceExpression
	1,  // 5: kotlin.ast.Node.class:type_name -> kotlin.ast.Class
	3,  // 6: kotlin.ast.Node.declaration_modifier_list:type_name -> kotlin.ast.DeclarationModifierList
	13, // 7: kotlin.ast.Node.primary_constructor:type_name -> kotlin.ast.PrimaryConstructor
	9,  // 8: kotlin.ast.Node.parameter:type_name -> kotlin.ast.Parameter
	10, // 9: kotlin.ast.Node.parameter_list:type_name -> kotlin.ast.ParameterList
	11, // 10: kotlin.ast.Node.type_reference:type_name -> kotlin.ast.TypeReference
	12, // 11: kotlin.ast.Node.user_type:type_name -> kotlin.ast.UserType
	7,  // 12: kotlin.ast.Node.nullable_type:type_name -> kotlin.ast.NullableType
	0,  // 13: kotlin.ast.Class.body:type_name -> kotlin.ast.Node
	3,  // 14: kotlin.ast.Class.modifiers:type_name -> kotlin.ast.DeclarationModifierList
	13, // 15: kotlin.ast.Class.constructor:type_name -> kotlin.ast.PrimaryConstructor
	0,  // 16: kotlin.ast.DotQualifiedExpression.receiver:type_name -> kotlin.ast.Node
	0,  // 17: kotlin.ast.DotQualifiedExpression.selector:type_name -> kotlin.ast.Node
	0,  // 18: kotlin.ast.File.body:type_name -> kotlin.ast.Node
	0,  // 19: kotlin.ast.NullableType.inner_type:type_name -> kotlin.ast.Node
	0,  // 20: kotlin.ast.PackageDirective.name:type_name -> kotlin.ast.Node
	11, // 21: kotlin.ast.Parameter.ref:type_name -> kotlin.ast.TypeReference
	9,  // 22: kotlin.ast.ParameterList.parameters:type_name -> kotlin.ast.Parameter
	0,  // 23: kotlin.ast.TypeReference.element:type_name -> kotlin.ast.Node
	6,  // 24: kotlin.ast.UserType.reference_expression:type_name -> kotlin.ast.NameReferenceExpression
	10, // 25: kotlin.ast.PrimaryConstructor.value_parameter_list:type_name -> kotlin.ast.ParameterList
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_kotlin_ast_proto_init() }
func file_kotlin_ast_proto_init() {
	if File_kotlin_ast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kotlin_ast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclarationModifierList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DotQualifiedExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameReferenceExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullableType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageDirective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kotlin_ast_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimaryConstructor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kotlin_ast_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Node_Comment)(nil),
		(*Node_File)(nil),
		(*Node_PackageDirective)(nil),
		(*Node_DotQualifiedExpression)(nil),
		(*Node_NameReferenceExpression)(nil),
		(*Node_Class)(nil),
		(*Node_DeclarationModifierList)(nil),
		(*Node_PrimaryConstructor)(nil),
		(*Node_Parameter)(nil),
		(*Node_ParameterList)(nil),
		(*Node_TypeReference)(nil),
		(*Node_UserType)(nil),
		(*Node_NullableType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kotlin_ast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kotlin_ast_proto_goTypes,
		DependencyIndexes: file_kotlin_ast_proto_depIdxs,
		MessageInfos:      file_kotlin_ast_proto_msgTypes,
	}.Build()
	File_kotlin_ast_proto = out.File
	file_kotlin_ast_proto_rawDesc = nil
	file_kotlin_ast_proto_goTypes = nil
	file_kotlin_ast_proto_depIdxs = nil
}
