// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repo

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

// 钉钉部门
type DingDept struct {
	// 部门id
	ID int64 `json:"id"`
	// 上级部门id
	Pid pgtype.Int8 `json:"pid"`
	// 部门名称
	Title pgtype.Text `json:"title"`
}

// 领域
type Domain struct {
	// 领域标签
	Tag string `json:"tag"`
	// 领域领导
	Leaders []string `json:"leaders"`
	// 领域配置
	Configs json.RawMessage `json:"configs"`
}
