// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package querytest

import (
	"context"
)

const getBars = `-- name: GetBars :many
SELECT FROM bar LIMIT 5
`

type GetBarsRow struct {
}

func (q *Queries) GetBars(ctx context.Context, aq ...AdditionalQuery) ([]GetBarsRow, error) {
	query := getBars
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBarsRow
	for rows.Next() {
		var i GetBarsRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
