// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Thing struct {
	ID      uint64
	Name    string
	Tag     sql.NullString
	Amount  float64
	Tags    []string
	Labels  []*string
	Matrix  [][]uint8
	Kind    sql.NullString
	Created time.Time
	Updated time.Time
	Price   decimal.Decimal
	Status  string
	Attrs   map[string]uint32
	Pos     []any
	Geo     map[string]any
	Scores  map[string]*uint8
	Ip      net.IP
	Uid     uuid.UUID
	Fixed   string
	Flag    bool
	Small   decimal.Decimal
	Plain   string
	Either  any
	NA      []uint8
	NB      []string
	Total   uint64
	Whole   int32
}
