// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package querytest

import (
	"context"
)

const barNotExists = `-- name: BarNotExists :one
SELECT 
    NOT EXISTS (
        SELECT
            1
        FROM
            bar
        WHERE
            id = ?
    )
`

func (q *Queries) BarNotExists(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, barNotExists)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
