// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package querytest

import (
	"context"
)

const dropEventTrigger = `-- name: DropEventTrigger :exec
DROP EVENT TRIGGER IF EXISTS my_event_trigger
`

func (q *Queries) DropEventTrigger(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropEventTrigger)
	return err
}

const dropTrigger = `-- name: DropTrigger :exec
DROP TRIGGER IF EXISTS my_trigger ON accounts
`

func (q *Queries) DropTrigger(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropTrigger)
	return err
}
