// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: aggfunc.sql

package querytest

import (
	"context"
	"database/sql"
)

const getAvg = `-- name: GetAvg :one
SELECT avg(int_val) FROM test
`

func (q *Queries) GetAvg(ctx context.Context, aq ...AdditionalQuery) (sql.NullFloat64, error) {
	query := getAvg
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var avg sql.NullFloat64
	err := row.Scan(&avg)
	return avg, err
}

const getCount = `-- name: GetCount :one
SELECT count(*) FROM test
`

func (q *Queries) GetCount(ctx context.Context, aq ...AdditionalQuery) (int64, error) {
	query := getCount
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCountId = `-- name: GetCountId :one
SELECT count(id) FROM test
`

func (q *Queries) GetCountId(ctx context.Context, aq ...AdditionalQuery) (int64, error) {
	query := getCountId
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupConcatInt = `-- name: GetGroupConcatInt :one
SELECT group_concat(int_val) FROM test
`

func (q *Queries) GetGroupConcatInt(ctx context.Context, aq ...AdditionalQuery) (string, error) {
	query := getGroupConcatInt
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var group_concat string
	err := row.Scan(&group_concat)
	return group_concat, err
}

const getGroupConcatInt2 = `-- name: GetGroupConcatInt2 :one
SELECT group_concat(1, ':') FROM test
`

func (q *Queries) GetGroupConcatInt2(ctx context.Context, aq ...AdditionalQuery) (string, error) {
	query := getGroupConcatInt2
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var group_concat string
	err := row.Scan(&group_concat)
	return group_concat, err
}

const getGroupConcatText = `-- name: GetGroupConcatText :one
SELECT group_concat(text_val) FROM test
`

func (q *Queries) GetGroupConcatText(ctx context.Context, aq ...AdditionalQuery) (string, error) {
	query := getGroupConcatText
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var group_concat string
	err := row.Scan(&group_concat)
	return group_concat, err
}

const getGroupConcatText2 = `-- name: GetGroupConcatText2 :one
SELECT group_concat(text_val, ':') FROM test
`

func (q *Queries) GetGroupConcatText2(ctx context.Context, aq ...AdditionalQuery) (string, error) {
	query := getGroupConcatText2
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var group_concat string
	err := row.Scan(&group_concat)
	return group_concat, err
}

const getMaxInt = `-- name: GetMaxInt :one
SELECT max(int_val) FROM test
`

func (q *Queries) GetMaxInt(ctx context.Context, aq ...AdditionalQuery) (interface{}, error) {
	query := getMaxInt
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getMaxText = `-- name: GetMaxText :one
SELECT max(text_val) FROM test
`

func (q *Queries) GetMaxText(ctx context.Context, aq ...AdditionalQuery) (interface{}, error) {
	query := getMaxText
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getMinInt = `-- name: GetMinInt :one
SELECT min(int_val) FROM test
`

func (q *Queries) GetMinInt(ctx context.Context, aq ...AdditionalQuery) (interface{}, error) {
	query := getMinInt
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getMinText = `-- name: GetMinText :one
SELECT min(text_val) FROM test
`

func (q *Queries) GetMinText(ctx context.Context, aq ...AdditionalQuery) (interface{}, error) {
	query := getMinText
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getSumInt = `-- name: GetSumInt :one
SELECT sum(int_val) FROM test
`

func (q *Queries) GetSumInt(ctx context.Context, aq ...AdditionalQuery) (sql.NullFloat64, error) {
	query := getSumInt
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var sum sql.NullFloat64
	err := row.Scan(&sum)
	return sum, err
}

const getSumText = `-- name: GetSumText :one
SELECT sum(text_val) FROM test
`

func (q *Queries) GetSumText(ctx context.Context, aq ...AdditionalQuery) (sql.NullFloat64, error) {
	query := getSumText
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var sum sql.NullFloat64
	err := row.Scan(&sum)
	return sum, err
}

const getTotalInt = `-- name: GetTotalInt :one
SELECT total(int_val) FROM test
`

func (q *Queries) GetTotalInt(ctx context.Context, aq ...AdditionalQuery) (float64, error) {
	query := getTotalInt
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var total float64
	err := row.Scan(&total)
	return total, err
}
