// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querytest

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v4"
)

type Querier interface {
	WithTx(tx pgx.Tx) *Queries
	CreateMemories(ctx context.Context, vampireID []uuid.UUID) ([]Memory, error)
	GetVampireIDs(ctx context.Context, vampireID []uuid.UUID) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
