// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
	"fmt"

	"example.com/mysql"
)

type JobStatusType string

const (
	APPLIED  JobStatusType = "APPLIED"
	PENDING  JobStatusType = "PENDING"
	ACCEPTED JobStatusType = "ACCEPTED"
	REJECTED JobStatusType = "REJECTED"
)

func (e *JobStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusType(s)
	case string:
		*e = JobStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusType: %T", src)
	}
	return nil
}

type Order struct {
	ID     mysql.ID
	Price  float64
	UserID int
}

func (t *Order) GetID() mysql.ID {
	return t.ID
}
func (t *Order) GetPrice() float64 {
	return t.Price
}
func (t *Order) GetUserID() int {
	return t.UserID
}

type User struct {
	ID        mysql.ID
	FirstName string
	LastName  sql.NullString
	Age       int
	JobStatus JobStatusType
	Created   mysql.Timestamp
}

func (t *User) GetID() mysql.ID {
	return t.ID
}
func (t *User) GetFirstName() string {
	return t.FirstName
}
func (t *User) GetLastName() sql.NullString {
	return t.LastName
}
func (t *User) GetAge() int {
	return t.Age
}
func (t *User) GetJobStatus() JobStatusType {
	return t.JobStatus
}
func (t *User) GetCreated() mysql.Timestamp {
	return t.Created
}
