// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organisation struct {
	PartyID   pgtype.UUID
	Name      string
	LegalName pgtype.Text
}

type Party struct {
	PartyID pgtype.UUID
	Name    string
}

type Person struct {
	PartyID   pgtype.UUID
	Name      string
	FirstName string
	LastName  string
}
