// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_batch.sql.go

package querytest

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// QueryBatch allows queuing multiple queries to be executed in a single
// round-trip using pgx v5's QueuedQuery callback pattern. Each Queue* method
// calls pgx.Batch.Queue and registers a result callback (QueryRow, Query, or
// Exec) that is invoked when ExecuteBatch processes the batch results.
// For :exec queries, no callback is needed - errors propagate via ExecuteBatch.
//
// The Batch field is exported to allow interoperability: callers can mix
// generated Queue* calls with custom pgx batch operations on the same
// underlying pgx.Batch.
type QueryBatch struct {
	Batch *pgx.Batch
}

// NewQueryBatch creates a new QueryBatch.
func NewQueryBatch() *QueryBatch {
	return &QueryBatch{
		Batch: &pgx.Batch{},
	}
}

// ExecuteBatch sends all queued queries and closes the batch.
func (q *Queries) ExecuteBatch(ctx context.Context, batch *QueryBatch) error {
	return q.db.SendBatch(ctx, batch.Batch).Close()
}

// QueueCreateAccount queues CreateAccount for batch execution.
// The callback fn is called when ExecuteBatch is called. The second parameter
// is false if the row was not found (no error is returned in this case).
func (b *QueryBatch) QueueCreateAccount(arg CreateAccountParams, fn func(Account, bool) error) {
	b.Batch.Queue(createAccount, arg.Name, arg.Balance).QueryRow(func(row pgx.Row) error {
		var i Account
		err := row.Scan(&i.ID, &i.Name, &i.Balance)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return fn(i, false)
			}
			return err
		}
		return fn(i, true)
	})
}

// QueueGetAccount queues GetAccount for batch execution.
// The callback fn is called when ExecuteBatch is called. The second parameter
// is false if the row was not found (no error is returned in this case).
func (b *QueryBatch) QueueGetAccount(id int32, fn func(Account, bool) error) {
	b.Batch.Queue(getAccount, id).QueryRow(func(row pgx.Row) error {
		var i Account
		err := row.Scan(&i.ID, &i.Name, &i.Balance)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return fn(i, false)
			}
			return err
		}
		return fn(i, true)
	})
}

// QueueListAccounts queues ListAccounts for batch execution.
// The callback fn is called with the results when ExecuteBatch is called.
func (b *QueryBatch) QueueListAccounts(fn func([]Account) error) {
	b.Batch.Queue(listAccounts).Query(func(rows pgx.Rows) error {
		defer rows.Close()
		var items []Account
		for rows.Next() {
			var i Account
			if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
				return err
			}
			items = append(items, i)
		}
		if err := rows.Err(); err != nil {
			return err
		}
		return fn(items)
	})
}

// QueueUpdateBalance queues UpdateBalance for batch execution.
func (b *QueryBatch) QueueUpdateBalance(arg UpdateBalanceParams) {
	b.Batch.Queue(updateBalance, arg.Balance, arg.ID)
}
