// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, name, tag, amount, uid, ip, big)
VALUES ({id:UInt64}, {name:String}, {tag:Nullable(String)}, {amount:Decimal(10, 2)}, {uid:UUID}, {ip:IPv4}, {big:Int128});
`

type InsertEventParams struct {
	ID     uint64
	Name   string
	Tag    *string
	Amount string
	Uid    string
	Ip     string
	Big    string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		sql.Named("id", arg.ID),
		sql.Named("name", arg.Name),
		sql.Named("tag", arg.Tag),
		sql.Named("amount", arg.Amount),
		sql.Named("uid", arg.Uid),
		sql.Named("ip", arg.Ip),
		sql.Named("big", arg.Big),
	)
	return err
}

const positionalEvent = `-- name: PositionalEvent :exec
INSERT INTO events (id, name, tag, amount, uid, ip, big)
VALUES (?, ?, ?, ?, ?, ?, ?);
`

type PositionalEventParams struct {
	ID     uint64
	Name   string
	Tag    *string
	Amount string
	Uid    string
	Ip     string
	Big    string
}

func (q *Queries) PositionalEvent(ctx context.Context, arg PositionalEventParams) error {
	_, err := q.db.ExecContext(ctx, positionalEvent,
		arg.ID,
		arg.Name,
		arg.Tag,
		arg.Amount,
		arg.Uid,
		arg.Ip,
		arg.Big,
	)
	return err
}

const repeatedName = `-- name: RepeatedName :many
SELECT id FROM events
WHERE name = {name:String} OR tag = {name:String} OR id = {id:UInt64};
`

type RepeatedNameParams struct {
	Name string
	ID   uint64
}

func (q *Queries) RepeatedName(ctx context.Context, arg RepeatedNameParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, repeatedName, sql.Named("name", arg.Name), sql.Named("id", arg.ID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uint64
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
