// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (
    pid,
    CustomerName
)
VALUES ($pid, $customer_name)
`

type InsertContactParams struct {
	Pid          string
	CustomerName *string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.ExecContext(ctx, insertContact, arg.Pid, arg.CustomerName)
	return err
}
