// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package querytest

import (
	"context"
)

const countStarLower = `-- name: CountStarLower :one
SELECT count(*) FROM bar
`

func (q *Queries) CountStarLower(ctx context.Context, aq ...AdditionalQuery) (int64, error) {
	query := countStarLower
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStarUpper = `-- name: CountStarUpper :one
SELECT COUNT(*) FROM bar
`

func (q *Queries) CountStarUpper(ctx context.Context, aq ...AdditionalQuery) (int64, error) {
	query := countStarUpper
	queryParams := []interface{}{}

	if len(aq) > 0 {
		query += " " + aq[0].SQL
		queryParams = append(queryParams, aq[0].Args...)
	}

	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}
