// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package querytest

import (
	"github.com/LukaGiorgadze/gonull"
)

type Foo struct {
	ID                    uint64
	SometimesBlankText    gonull.Nullable[string]
	SometimesBlankNumeric gonull.Nullable[int32]
}
