// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"

	"cloud.google.com/go/spanner"
)

type Thing struct {
	ID   int64
	S    sql.NullString
	Smax sql.NullString
	N    spanner.NullNumeric
	Byt  []byte
	Ai   []spanner.NullInt64
	As2  []spanner.NullString
	Ts   sql.NullTime
	D    spanner.NullDate
	J    spanner.NullJSON
	B    sql.NullBool
	F    sql.NullFloat64
	F32  spanner.NullFloat32
	U    spanner.NullUUID
}
