// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/sqlc-dev/sqlc-testdata/pkg"
)

type Override struct {
	ONE   pkg.CustomType
	Two   int64
	Three pkg.CustomType
	Four  []byte
	Five  []pkg.CustomType
}
