// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package querytest

import (
	"context"
)

const subqueryCalcColumn = `-- name: SubqueryCalcColumn :many
SELECT sum FROM (SELECT a + b AS sum FROM foo) AS f
`

func (q *Queries) SubqueryCalcColumn(ctx context.Context) ([]int32, error) {
	ctx, done := q.observer(ctx, "SubqueryCalcColumn")
	rows, err := q.db.QueryContext(ctx, subqueryCalcColumn)
	if err != nil {
		return nil, done(err)
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var sum int32
		if err := rows.Scan(&sum); err != nil {
			return nil, done(err)
		}
		items = append(items, sum)
	}
	if err := rows.Close(); err != nil {
		return nil, done(err)
	}
	if err := rows.Err(); err != nil {
		return nil, done(err)
	}
	return items, done(nil)
}
