// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type ChildTable struct {
	ID       int64  `json:"id"`
	ParentID int64  `json:"parent_id"`
	X        int32  `json:"x"`
	Y        string `json:"y"`
}

type ParentTable struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
