// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package date_and_time_functions

import (
	"database/sql"
)

type Student struct {
	StudentName sql.NullString
	TestScore   sql.NullFloat64
}
